package br.com.casa_guido.screens.cadastro.formularios.conjuge

enum class CamposConjuge {
    NOME_CONJUGE,
    CPF_CONJUGE,
    TELEFONE_CONJUGE,
    RG_CONJUGE,
    DATA_NASCIMENTO_CONJUGE,
    NATURALIDADE_CONJUGE,
    ESCOLARIDADE_CONJUGE,
    ESTADO_CIVIL_CONJUGE,
    SITUACAO_PROFISSIONAL_CONJUGE,
    SALARIO_CONJUGE,
    CARTAO_SUS
}