version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: casa_guido_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guido123456
      POSTGRES_DB: casa_guido
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
