package br.com.casa_guido.screens.cadastro.formularios.pai

enum class CamposResponsavel {
    NOME_RESPONSAVEL,
    RESP_PRINCIPAL,
    CPF_RESPONSAVEL,
    TELEFONE_RESPONSAVEL,
    RG_RESPONSAVEL,
    DATA_NASCIMENTO_RESPONSAVEL,
    NATURALIDADE_RESPONSAVEL,
    ESCOLARIDADE_RESPONSAVEL,
    ESTADO_CIVIL_RESPONSAVEL,
    SITUACAO_PROFISSIONAL_RESPONSAVEL,
    SALARIO_RESPONSAVEL,
    CARTAO_SUS,
    PROFISSAO
}